In [1]:
import numpy as np

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_ab_not = np.array([[0], [0], [1], [0]])
y_xor = np.array([[0], [1], [1], [0]])
y_combined = np.hstack((y_ab_not, y_xor))

input_size, hidden_size, output_size = 2, 2, 2
W1, b1 = np.random.rand(input_size, hidden_size), np.random.rand(hidden_size)
W2, b2 = np.random.rand(hidden_size, output_size), np.random.rand(output_size)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

learning_rate, epochs = 0.1, 10000

for epoch in range(epochs):
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)
    error = y_combined - a2
    
    dz2 = error * sigmoid_derivative(a2)
    W2 += learning_rate * np.dot(a1.T, dz2) / len(X)
    b2 += learning_rate * np.sum(dz2, axis=0) / len(X)
    
    dz1 = np.dot(dz2, W2.T) * sigmoid_derivative(a1)
    W1 += learning_rate * np.dot(X.T, dz1) / len(X)
    b1 += learning_rate * np.sum(dz1, axis=0) / len(X)

output = sigmoid(np.dot(sigmoid(np.dot(X, W1) + b1), W2) + b2)
print(np.round(output))

[[0. 0.]
 [0. 1.]
 [1. 1.]
 [0. 0.]]


In [19]:
import numpy as np

# Define the MLP class
class MLP:
    def __init__(self, input_size, hidden_size, output_size):
        self.W1 = np.random.rand(input_size, hidden_size)
        self.b1 = np.random.rand(hidden_size)
        self.W2 = np.random.rand(hidden_size, output_size)
        self.b2 = np.random.rand(output_size)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def train(self, X, y, epochs=10000, learning_rate=0.1):
        for epoch in range(epochs):
            # Forward pass
            z1 = np.dot(X, self.W1) + self.b1
            a1 = self.sigmoid(z1)
            z2 = np.dot(a1, self.W2) + self.b2
            a2 = self.sigmoid(z2)
            error = y - a2
            
            # Backward pass
            dz2 = error * self.sigmoid_derivative(a2)
            self.W2 += learning_rate * np.dot(a1.T, dz2) / len(X)
            self.b2 += learning_rate * np.sum(dz2, axis=0) / len(X)
            
            dz1 = np.dot(dz2, self.W2.T) * self.sigmoid_derivative(a1)
            self.W1 += learning_rate * np.dot(X.T, dz1) / len(X)
            self.b1 += learning_rate * np.sum(dz1, axis=0) / len(X)

    def predict(self, X):
        a1 = self.sigmoid(np.dot(X, self.W1) + self.b1)
        a2 = self.sigmoid(np.dot(a1, self.W2) + self.b2)
        return np.round(a2).astype(int)

# AND-NOT (AB') Gate Training
X_and_not = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_and_not = np.array([[0], [0], [1], [0]])
mlp_and_not = MLP(input_size=2, hidden_size=4, output_size=1)
mlp_and_not.train(X_and_not, y_and_not, epochs=5000)

# XOR Gate Training
X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_xor = np.array([[0], [1], [1], [0]])
mlp_xor = MLP(input_size=2, hidden_size=4, output_size=1)
mlp_xor.train(X_xor, y_xor, epochs=5000)

# Print training results
print("AND-NOT Function Predictions:")
print(mlp_and_not.predict(X_and_not))

print("\nXOR Function Predictions:")
print(mlp_xor.predict(X_xor))

# Manually test specific input values
and_not_test_input = np.array([[0, 1]])
xor_test_input = np.array([[1, 0]])

print("\nAND-NOT Function Prediction for input [0, 1]:")
print(mlp_and_not.predict(and_not_test_input))

print("\nXOR Function Prediction for input [1, 0]:")
print(mlp_xor.predict(xor_test_input))


AND-NOT Function Predictions:
[[0]
 [0]
 [1]
 [0]]

XOR Function Predictions:
[[0]
 [0]
 [1]
 [1]]

AND-NOT Function Prediction for input [0, 1]:
[[0]]

XOR Function Prediction for input [1, 0]:
[[1]]


In [17]:
print(mlp_and_not.predict(np.array([[0, 0]])))
print(mlp_and_not.predict(np.array([[0, 1]])))
print(mlp_and_not.predict(np.array([[1, 0]])))
print(mlp_and_not.predict(np.array([[1, 1]])))


[[0]]
[[0]]
[[1]]
[[0]]


In [15]:
print(mlp_xor.predict(np.array([[0, 0]])))
print(mlp_xor.predict(np.array([[0, 1]])))
print(mlp_xor.predict(np.array([[1, 0]])))
print(mlp_xor.predict(np.array([[1, 1]])))

[[0]]
[[1]]
[[1]]
[[1]]


In [9]:
# Without using keras

import numpy as np

# Activation function (sigmoid) and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Define the training data for AND-NOT function
X_and_not = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_and_not = np.array([[0], [0], [1], [0]])

# Define the training data for XOR function
X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_xor = np.array([[0], [1], [1], [0]])

# Define the Multi-layer Perceptron class with one hidden layer
class MLP:
    def __init__(self, input_size, hidden_size, output_size):
        # Initialize weights for input to hidden layer
        self.weights_input_hidden = np.random.rand(input_size, hidden_size)
        
        # Initialize weights for hidden to output layer
        self.weights_hidden_output = np.random.rand(hidden_size, output_size)
        
        # Initialize biases for hidden layer
        self.bias_hidden = np.random.rand(1, hidden_size)
        
        # Initialize biases for output layer
        self.bias_output = np.random.rand(1, output_size)

    def forward(self, X):
        # Forward pass through the hidden layer
        self.hidden = sigmoid(np.dot(X, self.weights_input_hidden) + self.bias_hidden)
        
        # Forward pass through the output layer
        self.output = sigmoid(np.dot(self.hidden, self.weights_hidden_output) + self.bias_output)
        return self.output

    def backward(self, X, y, output):
        # Calculate the error for the output layer
        output_error = y - output
        output_delta = output_error * sigmoid_derivative(output)

        # Calculate the error for the hidden layer
        hidden_error = output_delta.dot(self.weights_hidden_output.T)
        hidden_delta = hidden_error * sigmoid_derivative(self.hidden)

        # Update weights and biases
        self.weights_hidden_output += self.hidden.T.dot(output_delta)
        self.weights_input_hidden += X.T.dot(hidden_delta)
        self.bias_hidden += np.sum(hidden_delta, axis=0, keepdims=True)
        self.bias_output += np.sum(output_delta, axis=0, keepdims=True)

    def train(self, X, y, epochs):
        for _ in range(epochs):
            output = self.forward(X)
            self.backward(X, y, output)

    def predict(self, X):
        return (self.forward(X) > 0.5).astype(int)

# Training the MLP for AND-NOT function
mlp_and_not = MLP(input_size=2, hidden_size=4, output_size=1)
mlp_and_not.train(X_and_not, y_and_not, epochs=5000)

# Training the MLP for XOR function
mlp_xor2 = MLP(input_size=2, hidden_size=4, output_size=1)
mlp_xor2.train(X_xor, y_xor, epochs=5000)

# Print training results
print("AND-NOT Function Predictions:")
print(mlp_and_not.predict(X_and_not))

print("\nXOR Function Predictions:")
print(mlp_xor2.predict(X_xor))

# Manually test specific input values
and_not_test_input = np.array([[0, 1]])
xor_test_input = np.array([[1, 0]])

print("\nAND-NOT Function Prediction for input [0, 1]:")
print(mlp_and_not.predict(and_not_test_input))

print("\nXOR Function Prediction for input [1, 0]:")
print(mlp_xor2.predict(xor_test_input))

AND-NOT Function Predictions:
[[0]
 [0]
 [1]
 [0]]

XOR Function Predictions:
[[0]
 [1]
 [1]
 [0]]

AND-NOT Function Prediction for input [0, 1]:
[[0]]

XOR Function Prediction for input [1, 0]:
[[1]]
